<?php
/**
 * @file
 * Code for the VP Branduolys feature.
 */

include_once 'vp_core.features.inc';

function vp_core_date_formats() {
  return array(
    // Creates a new format for a new, custom format type.
    array(
      'type' => 'mysite_short_y_m_d',
      'format' => 'Y-m-d',
      'locales' => array(),
    ),
    // Defines a format and makes it available to core's short format type.
    array(
      'type' => 'short',
      'format' => 'Y-m-d',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
//function vp_core_date_format_types() {
//  return array(
//    'mysite_short_y_m_d' => t('Short: YYYY-MM-DD'),
//  );
//}

